// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages/Stamp.proto

#ifndef PROTOBUF_Messages_2fStamp_2eproto__INCLUDED
#define PROTOBUF_Messages_2fStamp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace MaxBotMessage {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Messages_2fStamp_2eproto();
void protobuf_AssignDesc_Messages_2fStamp_2eproto();
void protobuf_ShutdownFile_Messages_2fStamp_2eproto();

class Time;
class Stamp;

// ===================================================================

class Time : public ::google::protobuf::Message {
 public:
  Time();
  virtual ~Time();

  Time(const Time& from);

  inline Time& operator=(const Time& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Time& default_instance();

  void Swap(Time* other);

  // implements Message ----------------------------------------------

  Time* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Time& from);
  void MergeFrom(const Time& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 seconds_since_epoch = 1;
  inline bool has_seconds_since_epoch() const;
  inline void clear_seconds_since_epoch();
  static const int kSecondsSinceEpochFieldNumber = 1;
  inline ::google::protobuf::int32 seconds_since_epoch() const;
  inline void set_seconds_since_epoch(::google::protobuf::int32 value);

  // required int32 nanoseconds_since_seconds = 2;
  inline bool has_nanoseconds_since_seconds() const;
  inline void clear_nanoseconds_since_seconds();
  static const int kNanosecondsSinceSecondsFieldNumber = 2;
  inline ::google::protobuf::int32 nanoseconds_since_seconds() const;
  inline void set_nanoseconds_since_seconds(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MaxBotMessage.Time)
 private:
  inline void set_has_seconds_since_epoch();
  inline void clear_has_seconds_since_epoch();
  inline void set_has_nanoseconds_since_seconds();
  inline void clear_has_nanoseconds_since_seconds();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 seconds_since_epoch_;
  ::google::protobuf::int32 nanoseconds_since_seconds_;
  friend void  protobuf_AddDesc_Messages_2fStamp_2eproto();
  friend void protobuf_AssignDesc_Messages_2fStamp_2eproto();
  friend void protobuf_ShutdownFile_Messages_2fStamp_2eproto();

  void InitAsDefaultInstance();
  static Time* default_instance_;
};
// -------------------------------------------------------------------

class Stamp : public ::google::protobuf::Message {
 public:
  Stamp();
  virtual ~Stamp();

  Stamp(const Stamp& from);

  inline Stamp& operator=(const Stamp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stamp& default_instance();

  void Swap(Stamp* other);

  // implements Message ----------------------------------------------

  Stamp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stamp& from);
  void MergeFrom(const Stamp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .MaxBotMessage.Time time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline const ::MaxBotMessage::Time& time() const;
  inline ::MaxBotMessage::Time* mutable_time();
  inline ::MaxBotMessage::Time* release_time();
  inline void set_allocated_time(::MaxBotMessage::Time* time);

  // @@protoc_insertion_point(class_scope:MaxBotMessage.Stamp)
 private:
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::MaxBotMessage::Time* time_;
  friend void  protobuf_AddDesc_Messages_2fStamp_2eproto();
  friend void protobuf_AssignDesc_Messages_2fStamp_2eproto();
  friend void protobuf_ShutdownFile_Messages_2fStamp_2eproto();

  void InitAsDefaultInstance();
  static Stamp* default_instance_;
};
// ===================================================================


// ===================================================================

// Time

// required int32 seconds_since_epoch = 1;
inline bool Time::has_seconds_since_epoch() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Time::set_has_seconds_since_epoch() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Time::clear_has_seconds_since_epoch() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Time::clear_seconds_since_epoch() {
  seconds_since_epoch_ = 0;
  clear_has_seconds_since_epoch();
}
inline ::google::protobuf::int32 Time::seconds_since_epoch() const {
  // @@protoc_insertion_point(field_get:MaxBotMessage.Time.seconds_since_epoch)
  return seconds_since_epoch_;
}
inline void Time::set_seconds_since_epoch(::google::protobuf::int32 value) {
  set_has_seconds_since_epoch();
  seconds_since_epoch_ = value;
  // @@protoc_insertion_point(field_set:MaxBotMessage.Time.seconds_since_epoch)
}

// required int32 nanoseconds_since_seconds = 2;
inline bool Time::has_nanoseconds_since_seconds() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Time::set_has_nanoseconds_since_seconds() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Time::clear_has_nanoseconds_since_seconds() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Time::clear_nanoseconds_since_seconds() {
  nanoseconds_since_seconds_ = 0;
  clear_has_nanoseconds_since_seconds();
}
inline ::google::protobuf::int32 Time::nanoseconds_since_seconds() const {
  // @@protoc_insertion_point(field_get:MaxBotMessage.Time.nanoseconds_since_seconds)
  return nanoseconds_since_seconds_;
}
inline void Time::set_nanoseconds_since_seconds(::google::protobuf::int32 value) {
  set_has_nanoseconds_since_seconds();
  nanoseconds_since_seconds_ = value;
  // @@protoc_insertion_point(field_set:MaxBotMessage.Time.nanoseconds_since_seconds)
}

// -------------------------------------------------------------------

// Stamp

// required .MaxBotMessage.Time time = 1;
inline bool Stamp::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stamp::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stamp::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stamp::clear_time() {
  if (time_ != NULL) time_->::MaxBotMessage::Time::Clear();
  clear_has_time();
}
inline const ::MaxBotMessage::Time& Stamp::time() const {
  // @@protoc_insertion_point(field_get:MaxBotMessage.Stamp.time)
  return time_ != NULL ? *time_ : *default_instance_->time_;
}
inline ::MaxBotMessage::Time* Stamp::mutable_time() {
  set_has_time();
  if (time_ == NULL) time_ = new ::MaxBotMessage::Time;
  // @@protoc_insertion_point(field_mutable:MaxBotMessage.Stamp.time)
  return time_;
}
inline ::MaxBotMessage::Time* Stamp::release_time() {
  clear_has_time();
  ::MaxBotMessage::Time* temp = time_;
  time_ = NULL;
  return temp;
}
inline void Stamp::set_allocated_time(::MaxBotMessage::Time* time) {
  delete time_;
  time_ = time;
  if (time) {
    set_has_time();
  } else {
    clear_has_time();
  }
  // @@protoc_insertion_point(field_set_allocated:MaxBotMessage.Stamp.time)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MaxBotMessage

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Messages_2fStamp_2eproto__INCLUDED
